const Countries = [
  {
    id: 'GBR',
    code: 'GB',
    name: 'United Kingdom',
    provinces: [
      { id: 'GB-ABDN', code: 'ABDN', name: 'Aberdeenshire', country_id: 'SCOT' },
      { id: 'GB-ANGS', code: 'ANGS', name: 'Angus/Forfarshire', country_id: 'SCOT' },
      { id: 'GB-ARGL', code: 'ARGL', name: 'Argyllshire', country_id: 'SCOT' },
      { id: 'GB-AYRS', code: 'AYRS', name: 'Ayrshire', country_id: 'SCOT' },
      { id: 'GB-BANF', code: 'BANF', name: 'Banffshire', country_id: 'SCOT' },
      { id: 'GB-BUTE', code: 'BUTE', name: 'Buteshire', country_id: 'SCOT' },
      { id: 'GB-CLAK', code: 'CLAK', name: 'Clackmannanshire', country_id: 'SCOT' },
      { id: 'GB-CMTY', code: 'CMTY', name: 'Cromartyshire', country_id: 'SCOT' },
      { id: 'GB-DMBR', code: 'DMBR', name: 'Dunbartonshire/Dumbartonshire', country_id: 'SCOT' },
      { id: 'GB-DMFS', code: 'DMFS', name: 'Dumfriesshire', country_id: 'SCOT' },
      { id: 'GB-ELOTH', code: 'ELOTH', name: 'East Lothian/Haddingtonshire', country_id: 'SCOT' },
      { id: 'GB-FIFE', code: 'FIFE', name: 'Fife', country_id: 'SCOT' },
      { id: 'GB-INVER', code: 'INVER', name: 'Inverness-shire', country_id: 'SCOT' },
      { id: 'GB-KNDN', code: 'KNDN', name: 'Kincardineshire', country_id: 'SCOT' },
      { id: 'GB-KRCUD', code: 'KRCUD', name: 'Kirkcudbrightshire', country_id: 'SCOT' },
      { id: 'GB-KRSS', code: 'KRSS', name: 'Kinross-shire', country_id: 'SCOT' },
      { id: 'GB-LRKS', code: 'LRKS', name: 'Lanarkshire', country_id: 'SCOT' },
      { id: 'GB-MLOTH', code: 'MLOTH', name: 'Midlothian/Edinburghshire', country_id: 'SCOT' },
      { id: 'GB-MORAY', code: 'MORAY', name: 'Morayshire', country_id: 'SCOT' },
      { id: 'GB-NAIRN', code: 'NAIRN', name: 'Nairnshire', country_id: 'SCOT' },
      { id: 'GB-ORK', code: 'ORK', name: 'Orkney', country_id: 'SCOT' },
      { id: 'GB-PEEBS', code: 'PEEBS', name: 'Peeblesshire', country_id: 'SCOT' },
      { id: 'GB-PERTH', code: 'PERTH', name: 'Perthshire', country_id: 'SCOT' },
      { id: 'GB-RNFR', code: 'RNFR', name: 'Renfrewshire', country_id: 'SCOT' },
      { id: 'GB-ROSS', code: 'ROSS', name: 'Ross-shire', country_id: 'SCOT' },
      { id: 'GB-ROXB', code: 'ROXB', name: 'Roxburghshire', country_id: 'SCOT' },
      { id: 'GB-SELKS', code: 'SELKS', name: 'Selkirkshire', country_id: 'SCOT' },
      { id: 'GB-SHET', code: 'SHET', name: 'Shetland', country_id: 'SCOT' },
      { id: 'GB-STLNG', code: 'STLNG', name: 'Stirlingshire', country_id: 'SCOT' },
      { id: 'GB-SUTH', code: 'SUTH', name: 'Sutherland', country_id: 'SCOT' },
      { id: 'GB-WGNSH', code: 'WGNSH', name: 'Wigtownshire', country_id: 'SCOT' },
      { id: 'GB-WLOTH', code: 'WLOTH', name: 'West Lothian/Linlithgowshire', country_id: 'SCOT' },
      { id: 'GB-BDFD', code: 'BDFD', name: 'Bedfordshire', country_id: 'ENGL' },
      { id: 'GB-BRKS', code: 'BRKS', name: 'Berkshire', country_id: 'ENGL' },
      { id: 'GB-BUCKS', code: 'BUCKS', name: 'Buckinghamshire', country_id: 'ENGL' },
      { id: 'GB-BWKS', code: 'BWKS', name: 'Berwickshire', country_id: 'ENGL' },
      { id: 'GB-CAMBS', code: 'CAMBS', name: 'Cambridgeshire', country_id: 'ENGL' },
      { id: 'GB-CHES', code: 'CHES', name: 'Cheshire', country_id: 'ENGL' },
      { id: 'GB-CNWL', code: 'CNWL', name: 'Cornwall', country_id: 'ENGL' },
      { id: 'GB-CUMB', code: 'CUMB', name: 'Cumberland', country_id: 'ENGL' },
      { id: 'GB-DEVON', code: 'DEVON', name: 'Devon', country_id: 'ENGL' },
      { id: 'GB-DRBYS', code: 'DRBYS', name: 'Derbyshire', country_id: 'ENGL' },
      { id: 'GB-DRHM', code: 'DRHM', name: 'Durham', country_id: 'ENGL' },
      { id: 'GB-DRST', code: 'DRST', name: 'Dorset', country_id: 'ENGL' },
      { id: 'GB-ESSX', code: 'ESSX', name: 'Essex', country_id: 'ENGL' },
      { id: 'GB-GLOU', code: 'GLOU', name: 'Gloucestershire', country_id: 'ENGL' },
      { id: 'GB-HAMPS', code: 'HAMPS', name: 'Hampshire', country_id: 'ENGL' },
      { id: 'GB-HERTS', code: 'HERTS', name: 'Hertfordshire', country_id: 'ENGL' },
      { id: 'GB-HRFDS', code: 'HRFDS', name: 'Herefordshire', country_id: 'ENGL' },
      { id: 'GB-HUNTS', code: 'HUNTS', name: 'Huntingdonshire', country_id: 'ENGL' },
      { id: 'GB-KENT', code: 'KENT', name: 'Kent', country_id: 'ENGL' },
      { id: 'GB-LANCS', code: 'LANCS', name: 'Lancashire', country_id: 'ENGL' },
      { id: 'GB-LIECS', code: 'LIECS', name: 'Leicestershire', country_id: 'ENGL' },
      { id: 'GB-LINCS', code: 'LINCS', name: 'Lincolnshire', country_id: 'ENGL' },
      { id: 'GB-MSEX', code: 'MSEX', name: 'Middlesex', country_id: 'ENGL' },
      { id: 'GB-NFLK', code: 'NFLK', name: 'Norfolk', country_id: 'ENGL' },
      { id: 'GB-NHANTS', code: 'NHANTS', name: 'Northamptonshire', country_id: 'ENGL' },
      { id: 'GB-NHUMB', code: 'NHUMB', name: 'Northumberland', country_id: 'ENGL' },
      { id: 'GB-NOTTS', code: 'NOTTS', name: 'Nottinghamshire', country_id: 'ENGL' },
      { id: 'GB-OXFD', code: 'OXFD', name: 'Oxfordshire', country_id: 'ENGL' },
      { id: 'GB-RUTL', code: 'RUTL', name: 'Rutland', country_id: 'ENGL' },
      { id: 'GB-SFFK', code: 'SFFK', name: 'Suffolk', country_id: 'ENGL' },
      { id: 'GB-SHROPS', code: 'SHROPS', name: 'Shropshire', country_id: 'ENGL' },
      { id: 'GB-SOMST', code: 'SOMST', name: 'Somerset', country_id: 'ENGL' },
      { id: 'GB-STAFFS', code: 'STAFFS', name: 'Staffordshire', country_id: 'ENGL' },
      { id: 'GB-SURR', code: 'SURR', name: 'Surrey', country_id: 'ENGL' },
      { id: 'GB-SUSX', code: 'SUSX', name: 'Sussex', country_id: 'ENGL' },
      { id: 'GB-WILTS', code: 'WILTS', name: 'Wiltshire', country_id: 'ENGL' },
      { id: 'GB-WMLD', code: 'WMLD', name: 'Westmorland', country_id: 'ENGL' },
      { id: 'GB-WORCS', code: 'WORCS', name: 'Worcestershire', country_id: 'ENGL' },
      { id: 'GB-WWKS', code: 'WWKS', name: 'Warwickshire', country_id: 'ENGL' },
      { id: 'GB-YORKS', code: 'YORKS', name: 'Yorkshire', country_id: 'ENGL' },
      { id: 'NIRL-ARMG', code: 'ARMG', name: 'Armagh', country_id: 'NIRL' },
      { id: 'NIRL-ATRM', code: 'ATRM', name: 'Antrim', country_id: 'NIRL' },
      { id: 'NIRL-DOWN', code: 'DOWN', name: 'Down', country_id: 'NIRL' },
      { id: 'NIRL-FMNH', code: 'FMNH', name: 'Fermanagh', country_id: 'NIRL' },
      { id: 'NIRL-LDRY', code: 'LDRY', name: 'Londonderry', country_id: 'NIRL' },
      { id: 'NIRL-TYR', code: 'TYR', name: 'Tyrone', country_id: 'NIRL' },
      { id: 'GB-AGSY', code: 'AGSY', name: 'Anglesey/Sir Fon', country_id: 'WALS' },
      { id: 'GB-BREK', code: 'BREK', name: 'Brecknockshire/Sir Frycheiniog', country_id: 'WALS' },
      { id: 'GB-CDGN', code: 'CDGN', name: 'Cardiganshire/Ceredigion', country_id: 'WALS' },
      { id: 'GB-CMRN', code: 'CMRN', name: 'Carmarthenshire/Sir Gaerfyrddin', country_id: 'WALS' },
      { id: 'GB-CNFN', code: 'CNFN', name: 'Caernarfonshire/Sir Gaernarfon', country_id: 'WALS' },
      { id: 'GB-CTHN', code: 'CTHN', name: 'Caithness', country_id: 'WALS' },
      { id: 'GB-DENB', code: 'DENB', name: 'Denbighshire/Sir Ddinbych', country_id: 'WALS' },
      { id: 'GB-FTSH', code: 'FTSH', name: 'Flintshire/Sir Fflint', country_id: 'WALS' },
      { id: 'GB-GLAM', code: 'GLAM', name: 'Glamorgan/Morgannwg', country_id: 'WALS' },
      { id: 'GB-MIENT', code: 'MIENT', name: 'Merioneth/Meirionnydd', country_id: 'WALS' },
      { id: 'GB-MMTH', code: 'MMTH', name: 'Monmouthshire/Sir Fynwy', country_id: 'WALS' },
      { id: 'GB-MNTGS', code: 'MNTGS', name: 'Montgomeryshire/Sir Drefaldwyn', country_id: 'WALS' },
      { id: 'GB-PMBRK', code: 'PMBRK', name: 'Pembrokeshire/Sir Benfro', country_id: 'WALS' },
      { id: 'GB-RNRS', code: 'RNRS', name: 'Radnorshire/Sir Faesyfed', country_id: 'WALS' },
    ],
  },
];

export default Countries;
